### ISSUE TITLE
Doesn't work on a device 

### ISSUE THREAD

**Issue by jramini12** [leszek-s/LSLogViewer#1]
Works fine on the simulator, but when you actually test it on a device, the logs doesn't show

**Comment by Cellane** [comment]
Just noticed that this is happening on all of our iOS 10 devices as well. The root of the cause is the deprecation of Apple System Logger in favour of the new [Unified Logging System](https://developer.apple.com/documentation/os/logging?language=objc).

Unfortunately, while the new logging system should be faster and overall better than ASL, not everything from ASL got ported over. In particular, I don't think there is a method to search the log file on device at the moment, as `asl_search` function got deprecated without replacement (as discussed at the end of [this talk](https://developer.apple.com/videos/play/wwdc2016/721/) from WWDC 2016). I'm afraid at this moment, the only solution is to create a wrapper for `NSLog`/`os_log` that will call `NSLog`/`os_log` and also store the log message in a location that would be accessible for you later, such as app's database or something like that.

**Comment by leszek-s** [comment]
Yes. Due to changes made by Apple logs from NSLog can't be read on latest iOS versions therefore this lib was useless on recent devices so I decided to published a new version of the library which now save logs to own custom files saved in documents directory and instead of NSLog you just need to write LSLog to save them. You can also download your app container with xcode and it will also contain those log files saved with new LSLog.
